spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shirodemo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .html

mybatis:
  type-aliases-package: com.lijincan.pojo
  mybatis.mapper-locations: classpath:mapper/*.xml
